# Generated by Django 4.2.28 on 2026-02-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('selected_option', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.attempt')),
            ],
            options={
                'unique_together': {('attempt', 'question_id')},
            },
        ),
    ]
