# Generated by Django 4.2.28 on 2026-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_attempt_warning_count_candidateresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='questions_dump',
            field=models.TextField(default='[]'),
        ),
    ]
