# Generated by Django 4.2.7 on 2026-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_attempt_questions_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='sheet_gid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
